### ISSUE TITLE
VOC or COCO dataset model file

### ISSUE THREAD

**Issue by shivSD** [Tramac/Fast-SCNN-pytorch#19]
Hi,

  do you support voc or coco dataset ? if not can you guide me through the training process (changes need). Or if you support please can you share model files or script to train.

thanks for your help

**Comment by Tramac** [comment]
Hi, this project does not contain voc and coco, [this one](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/tree/master/core/data/dataloader) may help you.

**Comment by shivSD** [comment]
Thanks for the scripts. I did use pascal_voc.py to load the data. But i'm hitting into following error

Found 1464 images in the folder ../datasets/voc/VOC2012
Found 1449 images in the folder ../datasets/voc/VOC2012
w/ class balance
Starting Epoch: 0, Total Epochs: 160
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    trainer.train()
  File "train.py", line 127, in train
    for i, (images, targets) in enumerate(self.train_loader):
**ValueError: too many values to unpack (expected 2)**

Is it something to with torch version i'm using ?

**Comment by Liu6697** [comment]
Hi, @shivSD, I met the same error when use the pascal_voc.py, have you debugged it?

**Comment by BhargavaRamM** [comment]
@Liu6697 I think the problem is with what `enumerate(self.train_loader)` returns. If you notice, for city scapes dataset, `__getitem__(...)`method in `CitySegmentation` class returns `(img, mask)`. 
But in Pascal VOC data loader script from above reference returns `(img, mask, path)`. 
So, you will need to make sure you are unpacking all three items that `__getitem__(...)` methods returns when you enumerate(self.train_loader). 

Something like following should work:
```
for i, (images, targets, _) in enumerate(self.train_loader):
....
```

**Comment by Liu6697** [comment]
@BhargavaRamM Thanks!!!

**Comment by GUESSVPN** [comment]
Hi, @Liu6697 How about your trainning results on voc？
