### ISSUE TITLE
crop-size issue

### ISSUE THREAD

**Issue by zhangyuanxue** [Tramac/Fast-SCNN-pytorch#25]
when i change the default crop-size, it give the follow error:
------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zyx/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/zyx/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/zyx/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/zyx/anaconda3/envs/py36/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/zyx/anaconda3/envs/py36/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/zyx/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zyx/Fast-SCNN-pytorch/train.py", line 229, in <module>
    trainer.train()
  File "/home/zyx/Fast-SCNN-pytorch/train.py", line 153, in train
    outputs = self.model(images)
  File "/home/zyx/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyx/Fast-SCNN-pytorch/models/fast_scnn.py", line 37, in forward
    x = self.feature_fusion(higher_res_features, x)
  File "/home/zyx/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyx/Fast-SCNN-pytorch/models/fast_scnn.py", line 213, in forward
    out = higher_res_feature + lower_res_feature
RuntimeError: The size of tensor a (90) must match the size of tensor b (92) at non-singleton dimension 3
--------------------------------------------------------------------------------------
and i really do not konw why? can you give me any suggestion? thanks

**Comment by Sharpiless** [comment]
大佬我也遇到了这个问题，请问解决了吗？
