### ISSUE TITLE
runtime error while running eveal.py on voc datasets

### ISSUE THREAD

**Issue by GUESSVPN** [Tramac/Fast-SCNN-pytorch#32]
Hi,Thanks for your work.I have adapted the data_loder file of VOC from your another repo [https://github.com/Tramac/awesome-semantic-segmentation-pytorch](url) to train the VOC data.But when I went the validation step after my training, I met the runtime error as following:

`Namespace(aux=False, aux_weight=0.4, base_size=520, batch_size=2, crop_size=480, dataset='pascal_voc', device=device(type='cuda', index=0), epochs=160, eval=False, lr=0.01, model='fast_scnn', momentum=0.9, no_val=True, resume=None, save_folder='./weights', start_epoch=0, train_split='train', weight_decay=0.0001)
Found 1449 images in the folder ./datasets/voc/VOC2012
Finished loading model!
Testing model:  fast_scnn
Traceback (most recent call last):
  File "eval.py", line 62, in <module>
    evaluator.eval()
  File "eval.py", line 43, in eval
    outputs = self.model(image)
  File "/home/eli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eli/Fast-scnn_voc/models/fast_scnn.py", line 37, in forward
    x = self.feature_fusion(higher_res_features, x)
  File "/home/eli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eli/Fast-scnn_voc/models/fast_scnn.py", line 213, in forward
    out = higher_res_feature + lower_res_feature
RuntimeError: The size of tensor a (63) must match the size of tensor b (64) at non-singleton dimension 3
`
Is there some suggestion to solve this problem? Thanks.

**Comment by Tramac** [comment]
Maybe because of the input size.

**Comment by GUESSVPN** [comment]
Thanks a lot. So how should I change the crop_size of the input images?

**Comment by Tramac** [comment]
What is the current input size?

**Comment by GUESSVPN** [comment]
The crop-size now is 480,and I did have change it to 512, 500 or any others, but it doesn't work.Does it have any sense with the transforms.Normalize parameters? the current parameters is [.485, .456, .406], [.229, .224, .225]

**Comment by GUESSVPN** [comment]
Hi, there.I found the problem occurred when the tensor size of higher_res_feature doesn't match it with lower ones,  whose torch.size is now ([1, 128, 48, 64] and  ([1, 128, 46, 63] ) separately as you can see in my picture attached below.Would you please tell me how should I do next to make it works?
![IMG_20200609_115745](https://user-images.githubusercontent.com/52352713/84106463-c440b480-aa4d-11ea-82b1-34283b0c720b.jpg)

**Comment by Inquisitive-ME** [comment]
I also ran into this, except with a different size image. It seems like the Eval script is just broken.
```
RuntimeError: The size of tensor a (327) must match the size of tensor b (328) at non-singleton dimension 3
```
