### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by Linda-L** [Tramac/Fast-SCNN-pytorch#41]
There was no such problem during the first training. The same data set for the second training is reported as follows：

`Namespace(aux=False, aux_weight=0.4, base_size=1, batch_size=2, crop_size=768, dataset='citys', device=device(type='cuda', index=0), epochs=160, eval=False, lr=0.01, model='fast_scnn', momentum=0.9, no_val=True, resume=None, save_folder='./weights', start_epoch=0, train_split='train', weight_decay=0.0001)
Found 5 images in the folder ./datasets/citys/leftImg8bit/train
Found 3 images in the folder ./datasets/citys/leftImg8bit/val
w/ class balance
Starting Epoch: 0, Total Epochs: 160
Traceback (most recent call last):
  File "/home/lyl/000_Code/Fast-SCNN/train.py", line 200, in <module>
    trainer.train()
  File "/home/lyl/000_Code/Fast-SCNN/train.py", line 127, in train
    for i, (images, targets) in enumerate(self.train_loader):
  File "/home/lyl/anaconda3/envs/fastscnn1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/lyl/anaconda3/envs/fastscnn1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/lyl/000_Code/Fast-SCNN/data_loader/cityscapes.py", line 93, in __getitem__
    img, mask = self._sync_transform(img, mask)
  File "/home/lyl/000_Code/Fast-SCNN/data_loader/cityscapes.py", line 141, in _sync_transform
    img = img.resize((ow, oh), Image.BILINEAR)
  File "/home/lyl/anaconda3/envs/fastscnn1.0/lib/python3.6/site-packages/PIL/Image.py", line 1923, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0`

**Comment by Tramac** [comment]
Maybe some images have loading errors.

**Comment by Linda-L** [comment]
alright, thank you very much
